alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: bos-php-on-do
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: binaryops-ca-demo-app
region: sfo
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: mvoorberg/bos-php-on-do
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: bos-php-on-do
  run_command: pwd && ls && heroku-php-apache2 -C apache_app.conf
  source_dir: /src

